services:
  server:
    image: int-server
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:  
      - 55555:55555
    healthcheck:
      test: ["CMD-SHELL", "echo 0"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./:/app
    networks:
      - app-network

  client:
    image: int-client
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:  
      - 8000:8000
    volumes:
      - ./:/app
    depends_on:
      server:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    # driver: bridge